"""
Generated by AI Website Builder
Generic CRUD router — auto-generated from the data model.

Provides list / get / create / update / delete endpoints for every business
entity, with role-based read/write access and per-user scoping where required.
"""
from __future__ import annotations

from typing import List
from uuid import UUID

from fastapi import APIRouter, Depends, HTTPException, status
from sqlalchemy.orm import Session

from app.db import get_db
from app.deps import get_current_user
from app import models, schemas

router = APIRouter(prefix="/api", tags=["crud"])


def _role_of(user) -> str:
    return str(getattr(user, "role", "") or "").lower()


def _allowed(user, roles) -> bool:
    """True if the user's role is in the allowed set (case-insensitive).

    An empty allow-list, or an 'admin' role, always passes.
    """
    allowed = {str(r).lower() for r in (roles or [])}
    if not allowed:
        return True
    role = _role_of(user)
    return role == "admin" or role in allowed


def _scope_query(query, model_class, current_user, scope_fields):
    if _role_of(current_user) == "admin":
        return query
    for scope_field in scope_fields or []:
        if hasattr(model_class, scope_field):
            query = query.filter(getattr(model_class, scope_field) == current_user.id)
    return query


def _stamp_owner(data, model_class, current_user, scope_fields):
    if _role_of(current_user) == "admin":
        return data
    for scope_field in scope_fields or []:
        if hasattr(model_class, scope_field):
            data[scope_field] = current_user.id
    return data





# ---------------------------------------------------------------------------
# Note
# ---------------------------------------------------------------------------
@router.get("/notes", response_model=List[schemas.NoteRead])
def list_notes(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    if not _allowed(current_user, ["Admin", "User"]):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not allowed")
    query = db.query(models.Note)
    query = _scope_query(query, models.Note, current_user, ["user_id"])
    return query.all()


@router.get("/notes/{item_id}", response_model=schemas.NoteRead)
def get_notes(
    item_id: UUID,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    if not _allowed(current_user, ["Admin", "User"]):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not allowed")
    query = db.query(models.Note).filter(models.Note.id == item_id)
    query = _scope_query(query, models.Note, current_user, ["user_id"])
    obj = query.first()
    if not obj:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Note not found")
    return obj


@router.post("/notes", response_model=schemas.NoteRead, status_code=status.HTTP_201_CREATED)
def create_notes(
    payload: schemas.NoteCreate,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    if not _allowed(current_user, ["Admin", "User"]):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not allowed")
    data = _stamp_owner(payload.model_dump(exclude_unset=True), models.Note, current_user, ["user_id"])
    obj = models.Note(**data)
    db.add(obj)
    db.commit()
    db.refresh(obj)
    return obj


@router.put("/notes/{item_id}", response_model=schemas.NoteRead)
def update_notes(
    item_id: UUID,
    payload: schemas.NoteUpdate,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    if not _allowed(current_user, ["Admin", "User"]):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not allowed")
    query = db.query(models.Note).filter(models.Note.id == item_id)
    query = _scope_query(query, models.Note, current_user, ["user_id"])
    obj = query.first()
    if not obj:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Note not found")
    for key, value in payload.model_dump(exclude_unset=True).items():
        setattr(obj, key, value)
    db.commit()
    db.refresh(obj)
    return obj


@router.delete("/notes/{item_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_notes(
    item_id: UUID,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    if not _allowed(current_user, ["Admin", "User"]):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not allowed")
    query = db.query(models.Note).filter(models.Note.id == item_id)
    query = _scope_query(query, models.Note, current_user, ["user_id"])
    obj = query.first()
    if not obj:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Note not found")
    db.delete(obj)
    db.commit()
    return None





# ---------------------------------------------------------------------------
# Role
# ---------------------------------------------------------------------------
@router.get("/roles", response_model=List[schemas.RoleRead])
def list_roles(
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    if not _allowed(current_user, ["Admin", "User"]):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not allowed")
    query = db.query(models.Role)
    query = _scope_query(query, models.Role, current_user, [])
    return query.all()


@router.get("/roles/{item_id}", response_model=schemas.RoleRead)
def get_roles(
    item_id: UUID,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    if not _allowed(current_user, ["Admin", "User"]):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not allowed")
    query = db.query(models.Role).filter(models.Role.id == item_id)
    query = _scope_query(query, models.Role, current_user, [])
    obj = query.first()
    if not obj:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Role not found")
    return obj


@router.post("/roles", response_model=schemas.RoleRead, status_code=status.HTTP_201_CREATED)
def create_roles(
    payload: schemas.RoleCreate,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    if not _allowed(current_user, ["Admin"]):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not allowed")
    data = _stamp_owner(payload.model_dump(exclude_unset=True), models.Role, current_user, [])
    obj = models.Role(**data)
    db.add(obj)
    db.commit()
    db.refresh(obj)
    return obj


@router.put("/roles/{item_id}", response_model=schemas.RoleRead)
def update_roles(
    item_id: UUID,
    payload: schemas.RoleUpdate,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    if not _allowed(current_user, ["Admin"]):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not allowed")
    query = db.query(models.Role).filter(models.Role.id == item_id)
    query = _scope_query(query, models.Role, current_user, [])
    obj = query.first()
    if not obj:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Role not found")
    for key, value in payload.model_dump(exclude_unset=True).items():
        setattr(obj, key, value)
    db.commit()
    db.refresh(obj)
    return obj


@router.delete("/roles/{item_id}", status_code=status.HTTP_204_NO_CONTENT)
def delete_roles(
    item_id: UUID,
    db: Session = Depends(get_db),
    current_user=Depends(get_current_user),
):
    if not _allowed(current_user, ["Admin"]):
        raise HTTPException(status_code=status.HTTP_403_FORBIDDEN, detail="Not allowed")
    query = db.query(models.Role).filter(models.Role.id == item_id)
    query = _scope_query(query, models.Role, current_user, [])
    obj = query.first()
    if not obj:
        raise HTTPException(status_code=status.HTTP_404_NOT_FOUND, detail="Role not found")
    db.delete(obj)
    db.commit()
    return None


