from contextlib import asynccontextmanager
from pathlib import Path
from fastapi import Depends, FastAPI, Request, Response
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import JSONResponse
from sqlalchemy import func, select
from sqlalchemy.orm import Session

from app.db import engine, Base
from app import models
from app.deps import get_current_user, get_db
from app.routers.auth import router as auth_router
from app.routers.generic_crud import router as crud_router

_FRONTEND_DIR = Path(__file__).resolve().parent.parent / "frontend_templates"


def _serve_html(filename: str, inject: str = "") -> Response:
    path = _FRONTEND_DIR / filename
    if not path.exists():
        return JSONResponse({"error": f"{filename} not found"}, status_code=404)
    content = path.read_text(encoding="utf-8")
    if inject:
        content = content.replace("</head>", inject + "\n</head>") if "</head>" in content else inject + content
    return Response(
        content=content,
        media_type="text/html",
        headers={"Cache-Control": "no-cache, no-store, must-revalidate", "Pragma": "no-cache", "Expires": "0"},
    )


def _app_html(entity: str = "", mode: str = "dashboard", page_path: str = "") -> Response:
    inject = (
        "<script>"
        f"window.PAGE_ENTITY={entity!r};"
        f"window.PAGE_MODE={mode!r};"
        f"window.PAGE_PATH={page_path!r};"
        "</script>"
    )
    return _serve_html("app.html", inject)


@asynccontextmanager
async def lifespan(app: FastAPI):
    Base.metadata.create_all(bind=engine)
    yield


app = FastAPI(title='Personal Notes App', description="Auto-generated by AI Website Builder", version="1.0.0", lifespan=lifespan)
app.add_middleware(CORSMiddleware, allow_origins=["*"], allow_credentials=True, allow_methods=["*"], allow_headers=["*"])
app.include_router(auth_router)
app.include_router(crud_router)


@app.get("/health", tags=["health"])
def health():
    return {"status": "ok", "project": 'Personal Notes App'}


@app.get("/api", tags=["health"])
def api_root():
    return {"project": 'Personal Notes App', "ui": "/", "docs": "/docs", "health": "/health"}


def _role_ok(role: str, allowed: list[str]) -> bool:
    role = (role or "").lower()
    allowed = [a.lower() for a in allowed]
    if "any" in allowed:
        return True
    return role in allowed


@app.get("/api/dashboard/stats", tags=["dashboard"])
def api_dashboard_stats(
    db: Session = Depends(get_db),
    current_user: models.User = Depends(get_current_user),
):
    role = (current_user.role or "").lower()
    stats: dict = {}
    if _role_ok(role, ['Admin', 'User']):
        try:
            stats['notes'] = int(db.execute(select(func.count()).select_from(models.Note)).scalar_one() or 0)
        except Exception:
            stats['notes'] = None
    if _role_ok(role, ['Admin', 'User']):
        try:
            stats['roles'] = int(db.execute(select(func.count()).select_from(models.Role)).scalar_one() or 0)
        except Exception:
            stats['roles'] = None
    return stats


@app.get("/ui/login", response_class=Response, include_in_schema=False)
def ui_login(): return _serve_html("login.html")


@app.get("/ui/register", response_class=Response, include_in_schema=False)
def ui_register(): return _serve_html("register.html")


@app.get("/", response_class=Response, include_in_schema=False)
def ui_root(): return _app_html(mode="dashboard", page_path="/")


@app.get("/admin/dashboard", response_class=Response, include_in_schema=False)
def ui_admin(): return _app_html(mode="dashboard", page_path="/admin/dashboard")


@app.get("/ui/notes", response_class=Response, include_in_schema=False)
def ui_list_notes(): return _app_html(entity="Note", mode="list")

@app.get("/ui/notes/new", response_class=Response, include_in_schema=False)
def ui_new_notes(): return _app_html(entity="Note", mode="form")

@app.get("/ui/notes/{item_id}/edit", response_class=Response, include_in_schema=False)
def ui_edit_notes(item_id: str): return _app_html(entity="Note", mode="form")

@app.get("/ui/roles", response_class=Response, include_in_schema=False)
def ui_list_roles(): return _app_html(entity="Role", mode="list")

@app.get("/ui/roles/new", response_class=Response, include_in_schema=False)
def ui_new_roles(): return _app_html(entity="Role", mode="form")

@app.get("/ui/roles/{item_id}/edit", response_class=Response, include_in_schema=False)
def ui_edit_roles(item_id: str): return _app_html(entity="Role", mode="form")

@app.get("/notes", response_class=Response, include_in_schema=False)
def ui_page_3_notes(request: Request): return _app_html(entity="Note", mode="list", page_path="/notes")

@app.get("/notes/new", response_class=Response, include_in_schema=False)
def ui_page_4_notes_new(request: Request): return _app_html(entity="Note", mode="form", page_path="/notes/new")

@app.get("/notes/view/edit", response_class=Response, include_in_schema=False)
def ui_page_5_notes_view_edit(request: Request): return _app_html(entity="Note", mode="list", page_path="/notes/view/edit")

@app.get("/notes/view/delete", response_class=Response, include_in_schema=False)
def ui_page_6_notes_view_delete(request: Request): return _app_html(entity="Note", mode="list", page_path="/notes/view/delete")

@app.get("/shared-notes", response_class=Response, include_in_schema=False)
def ui_page_7_shared_notes(request: Request): return _app_html(entity="Note", mode="dashboard", page_path="/shared-notes")

@app.get("/users", response_class=Response, include_in_schema=False)
def ui_page_8_users(request: Request): return _app_html(entity="User", mode="list", page_path="/users")

@app.get("/admin/roles", response_class=Response, include_in_schema=False)
def ui_page_9_admin_roles(request: Request): return _app_html(entity="Role", mode="list", page_path="/admin/roles")

