"""
Generated by AI Website Builder
SQLAlchemy Models — auto-generated from data model
"""
from __future__ import annotations

import uuid
from datetime import datetime, date
from decimal import Decimal
from sqlalchemy import (
    Boolean, Column, Date, DateTime, Float,
    ForeignKey, Integer, Numeric, String, Text, func
)
from sqlalchemy.dialects.postgresql import UUID as PG_UUID
from sqlalchemy.types import TypeDecorator, CHAR
import uuid as _uuid

from app.db import Base


# ---------------------------------------------------------------------------
# UUID helper — works with both SQLite and PostgreSQL
# ---------------------------------------------------------------------------
class GUID(TypeDecorator):
    """Platform-independent GUID type.
    Uses PostgreSQL's UUID type, otherwise uses CHAR(36), storing as string.
    """
    impl = CHAR
    cache_ok = True

    def load_dialect_impl(self, dialect):
        if dialect.name == "postgresql":
            return dialect.type_descriptor(PG_UUID())
        return dialect.type_descriptor(CHAR(36))

    def process_bind_param(self, value, dialect):
        if value is None:
            return value
        if dialect.name == "postgresql":
            return str(value)
        if not isinstance(value, _uuid.UUID):
            return str(_uuid.UUID(str(value)))
        return str(value)

    def process_result_value(self, value, dialect):
        if value is None:
            return value
        if not isinstance(value, _uuid.UUID):
            return _uuid.UUID(str(value))
        return value


# ---------------------------------------------------------------------------
# Generated Models
# ---------------------------------------------------------------------------
class User(Base):
    __tablename__ = "users"

    id = Column(GUID, primary_key=True, default=_uuid.uuid4, nullable=False)
    email = Column(String(255), unique=True, index=True, nullable=False)
    password_hash = Column(String(255), nullable=False)
    role = Column(String(50), default="User", nullable=False)
    created_at = Column(DateTime, default=func.now(), nullable=False)
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now(), nullable=False)

    def __repr__(self):
        return f"<User email={self.email!r}>"






class Note(Base):
    __tablename__ = "notes"

    
    
    
    id = Column(GUID, primary_key=True, default=_uuid.uuid4, nullable=False)
    
    
    
    
    title = Column(String(255), unique=False, nullable=True)
    
    
    
    
    content = Column(Text, nullable=True)
    
    
    
    
    
    
    
        
        
    user_id = Column(GUID, ForeignKey("users.id"), nullable=True)
        
    
    
    
    
    
    
    created_at = Column(DateTime, default=func.now(), nullable=False)
    
    
    
    
    
    
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now(), nullable=False)
    
    
    

    def __repr__(self):
        return f"<Note id={self.id!r}>"



class Role(Base):
    __tablename__ = "roles"

    
    
    
    id = Column(GUID, primary_key=True, default=_uuid.uuid4, nullable=False)
    
    
    
    
    role_name = Column(String(255), unique=False, nullable=True)
    
    
    
    
    
    created_at = Column(DateTime, default=func.now(), nullable=False)
    
    
    
    
    
    
    updated_at = Column(DateTime, default=func.now(), onupdate=func.now(), nullable=False)
    
    
    

    def __repr__(self):
        return f"<Role id={self.id!r}>"


