"""
Generated by AI Website Builder
Pydantic Schemas — auto-generated from data model
"""
from __future__ import annotations

from datetime import datetime as DateTime, date as Date
from decimal import Decimal
from typing import Optional, List
from uuid import UUID
from pydantic import BaseModel, EmailStr, Field, ConfigDict

# ---------------------------------------------------------------------------
# Auth schemas (always present)
# ---------------------------------------------------------------------------
class UserCreate(BaseModel):
    email: EmailStr
    password: str = Field(min_length=6)
    role: str = Field(default="User")

class UserRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    id: UUID
    email: EmailStr
    role: str

class LoginRequest(BaseModel):
    email: EmailStr
    password: str

class Token(BaseModel):
    access_token: str
    token_type: str = "bearer"

class TokenData(BaseModel):
    user_id: Optional[str] = None
    role: Optional[str] = None

# ---------------------------------------------------------------------------
# Entity schemas (generated from data model)
# ---------------------------------------------------------------------------

# ---- Note ----

class NoteCreate(BaseModel):
    
    
    
    
    
    
    
    title: Optional[str] = None
    
    
    
    
    
    
    content: Optional[str] = None
    
    
    
    
    
    
    user_id: Optional[UUID] = None
    
    
    
    
    
    
    
    


class NoteUpdate(BaseModel):
    
    
    
    
    title: Optional[str] = None
    
    
    
    content: Optional[str] = None
    
    
    
    user_id: Optional[UUID] = None
    
    
    
    
    
    


class NoteRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    
    
    id: UUID
    
    
    
    title: Optional[str] = None
    
    
    
    content: Optional[str] = None
    
    
    
    user_id: UUID
    
    
    
    created_at: Optional[DateTime] = None
    
    
    
    updated_at: Optional[DateTime] = None
    
    


# ---- Role ----

class RoleCreate(BaseModel):
    
    
    
    
    
    
    
    role_name: Optional[str] = None
    
    
    
    
    
    
    
    


class RoleUpdate(BaseModel):
    
    
    
    
    role_name: Optional[str] = None
    
    
    
    
    
    


class RoleRead(BaseModel):
    model_config = ConfigDict(from_attributes=True)
    
    
    id: UUID
    
    
    
    role_name: Optional[str] = None
    
    
    
    created_at: Optional[DateTime] = None
    
    
    
    updated_at: Optional[DateTime] = None
    
    


