"""
Focused runtime validation and self-healing loop.

Scope: page loading, UI actions (buttons/forms/navigation), database CRUD.
"""

from __future__ import annotations

import json
import os
import re
import subprocess
import sys
import traceback
from dataclasses import dataclass, field
from datetime import datetime
from pathlib import Path
from typing import Any, Callable, Dict, List, Optional

from builder.contract_validator import ContractReport, repair_contract_issues, validate_generated_app_contract
from builder.runtime_app_server import RuntimeAppServer
from builder.runtime_test_generator import write_runtime_focused_tests
from builder.runtime_test_plan import build_runtime_test_plan, load_project_data
from builder.self_healing_agent import SelfHealingAgent


MAX_REPAIR_ATTEMPTS = 5
MAX_TOTAL_HEALING_ROUNDS = 15


def _restore_engine_contract(
    project_dir: str | Path,
    project_data: Dict[str, Any],
    log: Callable[[str], None],
) -> tuple[List[str], ContractReport]:
    """
    Restore deterministic engine-owned files after LLM repair attempts.

    Runtime healing may rewrite source files while chasing a focused failure. The
    core auth/CRUD/schema/seed/frontend contract is generated by the engine, so
    we reapply it before every retry to prevent one fix from deleting unrelated
    routes or breaking token handling.
    """
    root = Path(project_dir)
    written: List[str] = []
    try:
        from generated_apps.generator.deterministic_backend import apply_deterministic_guard
        from generated_apps.generator.repo_generator import (
            _default_public_role,
            _write_frontend_shell,
            _write_frontend_contract_page,
            _write_invariant_auth,
            _write_invariant_auth_router,
            _write_invariant_deps,
        )

        written.extend(apply_deterministic_guard(root, project_data, log=log))
        if _write_invariant_auth(root):
            written.append("app/auth.py")
        if _write_invariant_deps(root):
            written.append("app/deps.py")
        if _write_invariant_auth_router(root, _default_public_role(project_data)):
            written.append("app/routers/auth.py")
        theme = (
            (project_data.get("ui_selection") or {}).get("theme_vars")
            or (project_data.get("architecture") or {}).get("theme")
            or {}
        )
        _write_frontend_shell(root, project_data, theme)
        written.append("frontend_templates/index.html")
        written.append("frontend_templates/app.html")
        for rel in ("frontend_templates/entity_list.html", "frontend_templates/entity_form.html"):
            if _write_frontend_contract_page(root, rel):
                written.append(rel)
        (root / "app" / "__init__.py").write_text('"""Generated app package."""\n', encoding="utf-8")
        (root / "app" / "routers" / "__init__.py").write_text('"""Generated route package."""\n', encoding="utf-8")
        written.extend(["app/__init__.py", "app/routers/__init__.py"])
    except Exception as exc:
        log(f"[contract:warn] Could not restore deterministic engine contract: {exc}")

    contract = validate_generated_app_contract(root, project_data)
    if contract.ok:
        log(f"[contract] Engine contract restored ({len(set(written))} files)")
    else:
        details = "; ".join(f"{issue.file}: {issue.message}" for issue in contract.issues[:8])
        log(f"[contract:warn] Contract still has issues after restore: {details}")
    return sorted(set(written)), contract


@dataclass
class RuntimeFailure:
    test_id: str
    category: str  # page_load | ui_action | database
    feature: str
    error_snippet: str
    full_output: str
    repair_attempts: List[Dict[str, Any]] = field(default_factory=list)
    suspected_files: List[str] = field(default_factory=list)


def _parse_pytest_failures(output: str) -> List[RuntimeFailure]:
    failures: List[RuntimeFailure] = []
    blocks = re.split(r"(?=FAILED tests/test_runtime_focused\.py::)", output)
    for block in blocks:
        if "FAILED " not in block:
            continue
        m = re.search(
            r"FAILED tests/test_runtime_focused\.py::(\w+)\[?([^\]]*)\]?",
            block,
        )
        if not m:
            m = re.search(r"FAILED tests/test_runtime_focused\.py::(\w+)", block)
        if not m:
            continue
        func = m.group(1)
        param = (m.group(2) if m.lastindex and m.lastindex >= 2 else "").strip("[]'\"")

        category = "page_load"
        if func == "test_ui_action" or func == "test_dashboard_stats_no_errors":
            category = "ui_action"
        elif func.startswith("test_role"):
            category = "role_based"
        elif func.startswith("test_database"):
            category = "database"

        test_id = param or func
        feature = param or func
        err = block
        if "AssertionError" in block:
            err = block.split("AssertionError", 1)[-1][:1200]
        elif "E   " in block:
            err = "\n".join(line for line in block.splitlines() if line.strip().startswith("E "))[:1200]

        failures.append(
            RuntimeFailure(
                test_id=test_id,
                category=category,
                feature=feature,
                error_snippet=err.strip()[:800],
                full_output=block[-2500:],
            )
        )
    return failures


def _count_pytest_results(output: str) -> Dict[str, int]:
    passed = len(re.findall(r" PASSED", output))
    failed = len(re.findall(r" FAILED", output))
    errors = len(re.findall(r" ERROR", output))
    return {"passed": passed, "failed": failed, "errors": errors}


def _category_counts(plan, output: str) -> Dict[str, Dict[str, int]]:
    page_total = len(plan.pages)
    action_total = len(plan.actions) + 2  # dashboard stats + db init/me separate
    db_total = len([d for d in plan.database if d.operation not in ("init", "me")]) + 5
    role_total = len(plan.roles) + 2

    failed_ids = {f.test_id for f in _parse_pytest_failures(output)}

    page_failed = sum(
        1 for p in plan.pages
        if p.path in failed_ids or p.name in failed_ids
    )
    action_failed = sum(1 for a in plan.actions if a.test_id in failed_ids)
    if "test_dashboard_stats_no_errors" in output and "FAILED" in output:
        action_failed += 1
    db_failed = sum(1 for d in plan.database if d.test_id in failed_ids)
    role_failed = sum(1 for r in plan.roles if r.test_id in failed_ids)
    db_failed += sum(
        1
        for test_name in (
            "test_database_init",
            "test_database_auth_me",
            "test_database_form_login_compatibility",
            "test_seed_is_idempotent",
            "test_database_customer_lists_are_ownership_scoped",
        )
        if test_name in failed_ids
    )
    role_failed += int("test_role_public_registration_cannot_create_admin" in failed_ids)
    role_failed += int("test_database_customer_lists_are_ownership_scoped" in failed_ids)
    if "test_role_access" in output and "FAILED" in output and role_failed == 0:
        role_failed = output.count("test_role_access") and 1

    return {
        "page_load": {
            "total": page_total,
            "passed": max(0, page_total - page_failed),
            "failed": page_failed,
        },
        "ui_action": {
            "total": len(plan.actions) + 2,
            "passed": max(0, len(plan.actions) + 2 - action_failed),
            "failed": action_failed,
        },
        "database": {
            "total": db_total,
            "passed": max(0, db_total - db_failed),
            "failed": db_failed,
        },
        "role_based": {
            "total": role_total,
            "passed": max(0, role_total - role_failed),
            "failed": role_failed,
        },
    }


def _write_runtime_failure_report(
    project_dir: Path,
    failure: RuntimeFailure,
    repair_attempts: List[Dict[str, Any]],
    alternative: Dict[str, Any],
    final_passed: bool,
) -> Path:
    report_path = project_dir / "runtime_failure_report.txt"
    lines = [
        "Runtime Failure Report",
        "======================",
        "",
        f"Generated: {datetime.now().isoformat()}",
        "",
        f"Failure category: {failure.category}",
        f"Broken page or feature: {failure.feature}",
        f"Likely source file(s): {', '.join(failure.suspected_files) or 'see repair attempts'}",
        "",
        "Cause of the problem:",
        failure.error_snippet,
        "",
        "Runtime impact:",
        "Users could see Internal Server Error, broken navigation, non-working buttons/forms, "
        "or database CRUD failures for this feature.",
        "",
        "Repair attempts made:",
    ]
    for i, att in enumerate(repair_attempts, 1):
        lines.append(f"  Attempt {i}: {att.get('analysis', 'N/A')}")
        lines.append(f"    Files changed: {', '.join(att.get('files_changed', [])) or 'none'}")
    lines.extend([
        "",
        "Alternative solution (after 3 failed repair attempts):",
        alternative.get("analysis", "N/A"),
        f"Files changed: {', '.join(alternative.get('files_changed', [])) or 'none'}",
        "",
        f"Final test result: {'PASSED' if final_passed else 'STILL FAILING'}",
    ])
    report_path.write_text("\n".join(lines), encoding="utf-8")
    return report_path


def _guess_files(category: str, feature: str) -> List[str]:
    files = ["app/main.py", "frontend_templates/app.html"]
    if category == "database":
        files.extend(["app/models.py", "app/schemas.py", "app/routers/generic_crud.py", "seed.py"])
    if category == "ui_action":
        files.extend(
            [
                "frontend_templates/login.html",
                "frontend_templates/register.html",
                "app/routers/auth.py",
            ]
        )
    if "login" in feature.lower():
        files.append("frontend_templates/login.html")
    if "register" in feature.lower():
        files.append("frontend_templates/register.html")
    return list(dict.fromkeys(files))


class FocusedRuntimeHealer(SelfHealingAgent):
    """Self-healing specialized for runtime validation failures."""

    def _read_source_files(self) -> Dict[str, str]:
        result = super()._read_source_files()
        fe_dir = self.project_dir / "frontend_templates"
        if fe_dir.exists():
            for html_file in fe_dir.glob("*.html"):
                rel = f"frontend_templates/{html_file.name}"
                result[rel] = html_file.read_text(encoding="utf-8")
        return result

    def heal_runtime_failure(
        self,
        failure: RuntimeFailure,
        attempt: int,
        project_context: Dict[str, Any],
        server_logs: str = "",
    ) -> Dict[str, Any]:
        self._backup_current_files()
        source_files = self._read_source_files()
        for rel in _guess_files(failure.category, failure.feature):
            fp = self.project_dir / rel
            if fp.exists() and rel not in source_files:
                source_files[rel] = fp.read_text(encoding="utf-8")

        escalation = attempt - 1
        attempt_instructions = {
            1: "Apply the SMALLEST fix that addresses the root cause. Change only what is necessary.",
            2: "Inspect related routes, templates, forms, models, schemas, and imports. Apply a stronger fix.",
            3: "Trace the full flow (route → handler → schema → model → database → template/response) and fix the entire broken path.",
            4: "Compare auth, schemas, routes, database, seed, and frontend contracts. Rewrite every inconsistent file together.",
            5: "Use a simpler explicit implementation of the same feature. Preserve authorization and domain behavior.",
        }
        category_hints = {
            "page_load": "Fix HTTP 500/404 and ensure HTML renders with expected content. Check main.py routes and frontend_templates files.",
            "ui_action": "Fix buttons, form submit handlers (onsubmit), navigation links, dashboard stats API (/api/dashboard/stats), and auth API responses. Prefer reliable form POST over broken AJAX when needed.",
            "database": "Fix SQLAlchemy models, Pydantic schemas, CRUD routes, seed data, and DB initialization. Ensure columns match schema fields.",
            "role_based": "Fix role guards, login redirects, navigation filtering by role, dashboard stats visibility, and require_role() on admin-only API routes.",
        }

        ctx_summary = json.dumps(
            {
                "plain_text": (project_context.get("plain_text") or "")[:1200],
                "cleaned_spec": project_context.get("cleaned_spec", {}),
                "roles": (project_context.get("architecture", {}) or {}).get("roles", []),
                "pages": (project_context.get("architecture", {}) or {}).get("pages", []),
                "endpoints": (project_context.get("architecture", {}) or {}).get("endpoints", []),
                "data_model": project_context.get("data_model", {}),
            },
            ensure_ascii=False,
        )[:12000]
        budgeted_sources = {
            path: (
                content
                if len(content) <= 6500
                else content[:4800] + "\n# ... middle omitted ...\n" + content[-1500:]
            )
            for path, content in source_files.items()
        }

        prompt = f"""You are repairing a generated FastAPI web application after a REAL runtime test failure.

## Failure category: {failure.category}
## Broken feature: {failure.feature}
## Repair attempt: {attempt} of {MAX_REPAIR_ATTEMPTS}
## Instruction: {attempt_instructions.get(attempt, attempt_instructions[3])}
## Category guidance: {category_hints.get(failure.category, '')}

## User requirements (must preserve all features — do NOT remove functionality):
{ctx_summary}

## Test error:
```
{failure.full_output[-3500:]}
```

## Server logs (if any):
```
{server_logs[-2000:]}
```

## Source files:
```json
{json.dumps(budgeted_sources, indent=2, default=str)[:30000]}
```

## RULES:
1. Output ONLY valid JSON with "analysis", "confidence", "rewrites".
2. NEVER modify tests/*.py.
3. Do NOT remove user-facing features to make tests pass.
4. "content" must be the COMPLETE file when included.
5. Allowed files: app/*.py, app/routers/*.py, frontend_templates/*.html, seed.py.
   Never modify tests, requirements.txt, or environment files.
6. Plain source only: never add Jinja syntax or .j2 files.
7. Roles are stored exactly as the generated architecture roles and compared with .lower().
8. Preserve JSON login plus /login/form compatibility and ownership filtering for every non-admin role.

## OUTPUT SCHEMA:
{{"analysis": "...", "confidence": 0.0-1.0, "rewrites": [{{"file": "...", "reason": "...", "content": "..."}}]}}
"""
        raw = self.ask_llm(
            system="You are a Senior FastAPI engineer fixing real runtime failures in generated apps.",
            user=prompt,
            num_predict=6000,
        )
        result = self._parse_healing_response(raw)
        apply_result = self._apply_fixes(result.get("rewrites", []))
        files_changed = apply_result.get("applied", [])
        return {
            "success": bool(files_changed),
            "analysis": result.get("analysis", ""),
            "files_changed": files_changed,
            "attempt": attempt,
        }

    def apply_alternative_solution(
        self,
        failure: RuntimeFailure,
        project_context: Dict[str, Any],
        server_logs: str = "",
    ) -> Dict[str, Any]:
        self._backup_current_files()
        source_files = self._read_source_files()
        for rel in _guess_files(failure.category, failure.feature):
            fp = self.project_dir / rel
            if fp.exists():
                source_files[rel] = fp.read_text(encoding="utf-8")

        alternatives = {
            "page_load": "Add safe fallback data and ensure route serves static HTML even when dynamic data is missing.",
            "ui_action": "Replace fragile AJAX with /api/dashboard/stats for dashboard cards, or server-rendered counts. Use standard form POST for broken buttons.",
            "database": "Simplify schema/relationships while keeping required CRUD; ensure seed creates testable rows.",
            "role_based": "Use separate dashboard routes per role, server-side nav filtering, and explicit require_role('Admin') on admin-only endpoints.",
        }

        prompt = f"""After {MAX_REPAIR_ATTEMPTS} failed repair attempts, implement a SIMPLER but RELIABLE alternative that still satisfies the same user requirements.

## Failure: {failure.category} — {failure.feature}
## Strategy: {alternatives.get(failure.category, 'Simplify implementation')}

## Original error:
{failure.error_snippet}

## Server logs:
{server_logs[-2000:]}

## Requirements context:
{json.dumps(project_context.get('requirements', {}), ensure_ascii=False)[:4000]}

## Source:
```json
{json.dumps(source_files, indent=2, default=str)[:18000]}
```

Preserve ALL required features from user stories. Do not delete CRUD or auth — make them work reliably.

Output ONLY JSON: {{"analysis": "what alternative you used", "confidence": 0.0-1.0, "rewrites": [...]}}
"""
        raw = self.ask_llm(
            system="You implement safer alternative patterns in generated FastAPI apps without removing required features.",
            user=prompt,
            num_predict=8000,
        )
        result = self._parse_healing_response(raw)
        apply_result = self._apply_fixes(result.get("rewrites", []))
        return {
            "success": bool(apply_result.get("applied")),
            "analysis": result.get("analysis", ""),
            "files_changed": apply_result.get("applied", []),
        }


def run_focused_runtime_healing(
    project_dir: str,
    ask_llm_fn: Callable,
    project_data: Optional[Dict[str, Any]] = None,
    progress_callback: Optional[Callable[[str], None]] = None,
    venv_python: Optional[str] = None,
    env: Optional[Dict[str, str]] = None,
) -> Dict[str, Any]:
    """
    Full pipeline: start app → run focused tests → heal (3x per failure) → alternative → final suite.
    """
    project_path = Path(project_dir)
    project_data = project_data or load_project_data(project_dir)
    healer = FocusedRuntimeHealer(
        project_dir,
        ask_llm_fn,
        progress_callback,
        max_total_cycles=MAX_TOTAL_HEALING_ROUNDS,
        project_context=project_data,
    )
    python_exe = venv_python or sys.executable
    run_env = dict(env or os.environ.copy())
    run_env.setdefault("DATABASE_URL", "sqlite:///./runtime_test.db")

    plan = build_runtime_test_plan(project_data)
    contract = ContractReport(ok=True, issues=[])
    contract_repaired: List[str] = []

    healer.log("📋 Building focused runtime test suite...")
    write_runtime_focused_tests(project_dir, project_data)
    restored, contract = _restore_engine_contract(project_path, project_data, healer.log)
    contract_repaired.extend(restored)

    from builder.python_syntax import validate_project_python_files

    syntax_issues = validate_project_python_files(project_dir)
    if syntax_issues:
        healer.log("Python syntax errors found; invoking project-aware repair")
        syntax_text = "\n".join(f"{i.path}: {i.message}" for i in syntax_issues)
        syntax_failure = RuntimeFailure(
            test_id="syntax_preflight",
            category="page_load",
            feature="Application syntax preflight",
            error_snippet=syntax_text[:800],
            full_output=syntax_text,
        )
        for attempt in range(1, MAX_REPAIR_ATTEMPTS + 1):
            healer.heal_runtime_failure(syntax_failure, attempt, project_data)
            restored, contract = _restore_engine_contract(project_path, project_data, healer.log)
            contract_repaired.extend(restored)
            syntax_issues = validate_project_python_files(project_dir)
            if not syntax_issues:
                break
        if syntax_issues:
            names = ", ".join(f"{i.path}: {i.message}" for i in syntax_issues)
            return {
                "success": False,
                "error": f"Python syntax errors in generated app: {names}",
                "repair_attempts": 0,
                "summary": _build_summary(plan, "", False, 0),
            }

    healer.log("🔍 Running backend contract validation...")
    contract = validate_generated_app_contract(project_dir, project_data)
    if not contract.ok:
        healer.log(f"Contract issues found ({len(contract.issues)}); invoking project-aware repair")
        contract_text = "\n".join(
            f"{issue.file}: {issue.message}" for issue in contract.issues
        )
        contract_failure = RuntimeFailure(
            test_id="contract_preflight",
            category="database",
            feature="Generated application contract",
            error_snippet=contract_text[:800],
            full_output=contract_text,
        )
        for attempt in range(1, MAX_REPAIR_ATTEMPTS + 1):
            result = healer.heal_runtime_failure(
                contract_failure,
                attempt,
                project_data,
            )
            contract_repaired.extend(result.get("files_changed", []))
            restored, contract = _restore_engine_contract(project_path, project_data, healer.log)
            contract_repaired.extend(restored)
            contract = validate_generated_app_contract(project_dir, project_data)
            if contract.ok:
                break
        if contract.ok:
            healer.log("✅ Contract validation passed after repair")
        else:
            healer.log(f"⚠️ {len([i for i in contract.issues if i.severity == 'error'])} contract error(s) remain")

    req_file = project_path / "requirements.txt"
    if req_file.exists():
        healer.log("📦 Installing app and test dependencies...")
        subprocess.run(
            [
                str(python_exe),
                "-m",
                "pip",
                "install",
                "-q",
                "-r",
                str(req_file),
                "pytest",
                "pytest-asyncio",
                "httpx",
                "requests",
                "uvicorn",
            ],
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=300,
            env=run_env,
        )

    repair_attempts_total = 0
    alternative_reports: List[Path] = []
    last_output = ""
    server_logs = ""

    def run_tests(live_url: str) -> subprocess.CompletedProcess:
        test_env = dict(run_env)
        test_env["RUNTIME_TEST_BASE_URL"] = live_url
        return subprocess.run(
            [
                str(python_exe),
                "-m",
                "pytest",
                "tests/test_runtime_focused.py",
                "-v",
                "--tb=short",
                "-m",
                "page_load or ui_action or database or role_based",
            ],
            cwd=project_dir,
            capture_output=True,
            text=True,
            timeout=300,
            env=test_env,
        )

    healer.log("🚀 Starting generated app (live HTTP runtime)...")
    try:
        with RuntimeAppServer(
            project_dir,
            python_exe,
            run_env,
            reset_database=True,
            log=healer.log,
        ) as server:
            healer.log(f"✅ Server ready at {server.base_url}")

            pr = run_tests(server.base_url)
            last_output = pr.stdout + "\n" + pr.stderr
            server_logs = server.read_logs()

            failures = _parse_pytest_failures(last_output)
            if pr.returncode == 0:
                healer.log("✅ All focused runtime tests passed on first run!")
            else:
                healer.log(f"❌ {len(failures)} failure group(s) detected — starting self-healing...")

            attempt_by_failure: Dict[str, int] = {}
            for _round in range(MAX_TOTAL_HEALING_ROUNDS):
                if pr.returncode == 0:
                    break
                failures = _parse_pytest_failures(last_output)
                if not failures:
                    break

                failure = failures[0]
                key = f"{failure.category}:{failure.test_id}"
                attempt = attempt_by_failure.get(key, 0) + 1

                if attempt <= MAX_REPAIR_ATTEMPTS:
                    healer.log(
                        f"🔧 Repair attempt {attempt}/{MAX_REPAIR_ATTEMPTS} "
                        f"for [{failure.category}] {failure.feature}"
                    )
                    result = healer.heal_runtime_failure(
                        failure, attempt, project_data, server_logs
                    )
                    repair_attempts_total += 1
                    failure.repair_attempts.append(result)
                    failure.suspected_files = result.get("files_changed", [])
                    attempt_by_failure[key] = attempt
                    restored, contract = _restore_engine_contract(project_path, project_data, healer.log)
                    contract_repaired.extend(restored)
                else:
                    healer.log(f"🔄 Applying alternative solution for {failure.feature}...")
                    alt = healer.apply_alternative_solution(
                        failure, project_data, server_logs
                    )
                    repair_attempts_total += 1
                    failure.suspected_files = alt.get("files_changed", [])
                    restored, contract = _restore_engine_contract(project_path, project_data, healer.log)
                    contract_repaired.extend(restored)
                    subprocess.run(
                        [str(python_exe), "seed.py"],
                        cwd=project_dir,
                        capture_output=True,
                        env=run_env,
                        timeout=120,
                    )
                    server.restart()
                    pr = run_tests(server.base_url)
                    last_output = pr.stdout + "\n" + pr.stderr
                    server_logs = server.read_logs()
                    report = _write_runtime_failure_report(
                        project_path,
                        failure,
                        failure.repair_attempts,
                        alt,
                        final_passed=(pr.returncode == 0),
                    )
                    alternative_reports.append(report)
                    healer.log(f"📄 Wrote {report.name}")
                    attempt_by_failure[key] = 0
                    continue

                from builder.seed_runner import run_seed

                run_seed(
                    project_path,
                    str(python_exe),
                    project_data=project_data,
                    extra_env=run_env,
                    timeout=120,
                    retry_with_repair=False,
                )
                server.restart()
                pr = run_tests(server.base_url)
                last_output = pr.stdout + "\n" + pr.stderr
                server_logs = server.read_logs()

    except RuntimeError as start_err:
        healer.log(f"❌ Could not start app: {start_err}")
        last_output = str(start_err)
        startup_failure = RuntimeFailure(
            test_id="app_start",
            category="page_load",
            feature="Application startup",
            error_snippet=str(start_err)[:800],
            full_output=str(start_err),
        )
        startup_recovered = False
        for attempt in range(1, MAX_REPAIR_ATTEMPTS + 1):
            healer.heal_runtime_failure(
                startup_failure,
                attempt,
                project_data,
                server_logs,
            )
            repair_attempts_total += 1
            restored, contract = _restore_engine_contract(project_path, project_data, healer.log)
            contract_repaired.extend(restored)
            try:
                with RuntimeAppServer(
                    project_dir,
                    python_exe,
                    run_env,
                    reset_database=True,
                    log=healer.log,
                ) as retry_server:
                    pr = run_tests(retry_server.base_url)
                    last_output = pr.stdout + "\n" + pr.stderr
                    server_logs = retry_server.read_logs()
                    startup_recovered = pr.returncode == 0
                if startup_recovered:
                    break
            except RuntimeError as retry_error:
                startup_failure.full_output = str(retry_error)
                startup_failure.error_snippet = str(retry_error)[:800]
        if startup_recovered:
            summary = _build_summary(plan, last_output, True, repair_attempts_total)
            _write_runtime_validation_summary(project_path, summary)
            return {
                "success": True,
                "repair_attempts": repair_attempts_total,
                "summary": summary,
                "last_test_output": last_output[-3000:],
            }
        from builder.failure_classifier import classify_failure

        diagnostic_output = "\n".join(part for part in (last_output, server_logs) if part)
        diagnosis = classify_failure(project_data, diagnostic_output, repair_attempts_total)
        return {
            "success": False,
            "error": str(start_err),
            "repair_attempts": repair_attempts_total,
            "summary": _build_summary(plan, last_output, False, repair_attempts_total),
            "last_test_output": diagnostic_output[-3000:],
            "diagnosis": diagnosis,
        }

    success = pr.returncode == 0
    healer.state.mark_complete(success)

    if success:
        healer.log("🎉 Final focused runtime test suite: ALL PASSED")
    else:
        healer.log("⚠️ Some focused runtime tests still failing after healing")

    summary = _build_summary(plan, last_output, success, repair_attempts_total)
    summary["healing"] = healer.get_summary()
    summary["alternative_reports"] = [str(p) for p in alternative_reports]
    summary["contract_validation"] = contract.to_dict() if contract else {}
    summary["contract_repaired_files"] = contract_repaired

    _write_runtime_validation_summary(project_path, summary)

    diagnosis = None
    if not success:
        try:
            from builder.failure_classifier import classify_failure

            diagnostic_output = "\n".join(part for part in (last_output, server_logs) if part)
            diagnosis = classify_failure(project_data, diagnostic_output, repair_attempts_total)
            healer.log(
                "Failure diagnosis: "
                f"{diagnosis['category']} (confidence {diagnosis['confidence']}) - "
                f"{diagnosis['reason']}"
            )
        except Exception as diag_err:
            healer.log(f"Could not run failure diagnosis: {diag_err}")

    return {
        "success": success,
        "repair_attempts": repair_attempts_total,
        "summary": summary,
        "last_test_output": "\n".join(part for part in (last_output, server_logs) if part)[-3000:],
        "diagnosis": diagnosis,
    }


def _write_runtime_validation_summary(project_dir: Path, summary: Dict[str, Any]) -> Path:
    out = project_dir / "runtime_validation_summary.txt"
    pl = summary.get("page_load_tests", {})
    ui = summary.get("ui_action_tests", {})
    db = summary.get("database_tests", {})
    rb = summary.get("role_based_tests", {})
    lines = [
        "Runtime Validation Summary",
        "==========================",
        "",
        f"Final status: {summary.get('final_status', 'UNKNOWN')}",
        "",
        "Page tests:",
        f"  total: {pl.get('total', 0)}",
        f"  passed: {pl.get('passed', 0)}",
        f"  failed: {pl.get('failed', 0)}",
        "",
        "Button/navigation/form tests:",
        f"  total: {ui.get('total', 0)}",
        f"  passed: {ui.get('passed', 0)}",
        f"  failed: {ui.get('failed', 0)}",
        "",
        "Database tests:",
        f"  total: {db.get('total', 0)}",
        f"  passed: {db.get('passed', 0)}",
        f"  failed: {db.get('failed', 0)}",
        "",
        "Role-based tests:",
        f"  total: {rb.get('total', 0)}",
        f"  passed: {rb.get('passed', 0)}",
        f"  failed: {rb.get('failed', 0)}",
        "",
        f"Repair attempts used: {summary.get('repair_attempts_used', 0)}",
    ]
    contract = summary.get("contract_validation") or {}
    if contract:
        lines.extend([
            "",
            f"Contract validation: {'PASSED' if contract.get('ok') else 'ISSUES FOUND'}",
            f"Contract issues: {len(contract.get('issues') or [])}",
        ])
    out.write_text("\n".join(lines), encoding="utf-8")
    return out


def _build_summary(
    plan,
    output: str,
    success: bool,
    repair_attempts: int,
) -> Dict[str, Any]:
    counts = _category_counts(plan, output)
    pl, ui, db, rb = counts["page_load"], counts["ui_action"], counts["database"], counts["role_based"]
    if success:
        pl = {**pl, "passed": pl["total"], "failed": 0}
        ui = {**ui, "passed": ui["total"], "failed": 0}
        db = {**db, "passed": db["total"], "failed": 0}
        rb = {**rb, "passed": rb["total"], "failed": 0}
    return {
        "final_status": "PASSED" if success else "FAILED",
        "page_load_tests": pl,
        "ui_action_tests": ui,
        "database_tests": db,
        "role_based_tests": rb,
        "repair_attempts_used": repair_attempts,
        "total_page_loading_tests": pl["total"],
        "passed_page_loading_tests": pl["passed"],
        "failed_page_loading_tests": pl["failed"],
        "total_button_form_navigation_tests": ui["total"],
        "passed_button_form_navigation_tests": ui["passed"],
        "failed_button_form_navigation_tests": ui["failed"],
        "total_database_tests": db["total"],
        "passed_database_tests": db["passed"],
        "failed_database_tests": db["failed"],
        "total_role_based_tests": rb["total"],
        "passed_role_based_tests": rb["passed"],
        "failed_role_based_tests": rb["failed"],
    }
